// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocketMessageType } from "./SocketMessageType";

export type SocketMessage = { type: SocketMessageType, value: string | undefined, username: string | undefined, };
